---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: HOST
  user: root
  ssh_key:
    from_secret: SSH_KEY

steps:
- name: greeting
  commands:
  - echo "Testing ssh runner"

trigger:
  branch:
  - main
