---
kind: pipeline
type: ssh
name: default

platform:
  os: linux
  arch: amd64

server:
  host: ${{ secrets.HOST }}
  user: root
  ssh_key:
    from_secret: ${{ secrets.SSH_KEY }}

steps:
- name: greeting
  commands:
  - echo "Testing ssh runner"

trigger:
  branch:
  - main
