---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

metadata:
  namespace: default

steps:
- name: greeting
  image: ubuntu:20.04
  commands:
  - echo "testing docker runner"

trigger:
  branch:
  - main
