---
kind: pipeline
type: ssh
name: default

platform:
  os: linux
  arch: amd64

server:
  host: 
    from_secret: host
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
- name: greeting
  commands:
  - echo "Testing ssh runner"

trigger:
  branch:
  - main
