---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: ppc64le

steps:
- name: greeting
  image: ubuntu:20.04
  commands:
  - echo "testing triggers on drone server on power"

trigger:
  branch:
  - main
