---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: ppc64

steps:
- name: greeting
  image: ubuntu:20.04
  commands:
  - echo "testing docker runner"

trigger:
  branch:
  - main
